import Head from "next/head";
import React from "react";
import Header from "./Header";

type Props = { children: any };

export default function Layout({ children }: Props) {
  return (
    <div className="flex-1 w-screen overflow-x-hidden min-h-screen flex flex-col font-body text-white bg-[rgb(36,36,36)]">
      <Head>
        <title>Valorant Clutcher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex-1 flex">{children}</main>
    </div>
  );
}
